(quote (a b c))
(atom 'a)
(atom '(a b c))
(atom '())
(atom (atom 'a))
(atom '(atom 'a))
(eq 'a 'a)
(eq 'a 'b)
(eq '() '())
(car '(a b c))
(cdr '(a b c))
(cons 'a '(b c))
(cons 'a (cons 'b (cons 'c '())))
(car (cons 'a '(b c)))
(cdr (cons 'a '(b c)))
(cond ((eq 'a 'b) 'first)
        ((atom 'a)  'second))
(cond ((eq 'a 'b) 'first)
        ((atom 'a)  'second))
((lambda (a b) (+ a b)) 4 5)

